version: "3.9"

services:
  contaxy:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "30010:8080"
    networks:
      - test-contaxy-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - s3
  db:
    image: postgres:13.2
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - test-contaxy-network
  s3:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    networks:
      - test-contaxy-network

networks:
  test-contaxy-network:
